# name: Docker Image CI

# on:
#   push:
#     branches: [ "dev" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20.11.0"  # Adjust node version as needed

#       # Add this step to change to the root directory
#       - name: Change to root directory
#         run: cd $GITHUB_WORKSPACE    

#       - name: Install dependencies - Admin
#         run: |
#           npm install
#         env:
#           CI: ""
#         working-directory: ./admindashboard

#       - name: Build - Admin
#         run: |
#           npm run build
#         working-directory: ./admindashboard

#       - name: Install dependencies - Socialsphere
#         run: |
#           npm install
#         env:
#           CI: ""
#         working-directory: ./socialsphere

#       - name: Build - Socialsphere
#         run: |
#           npm run build
#         working-directory: ./socialsphere

#       - name: Install dependencies - Homepage
#         run: |
#           npm install
#         env:
#           CI: ""
#         working-directory: ./Homepage

#       - name: Build - Homepage
#         run: |
#           npm run build
#         working-directory: ./Homepage

#       - name: Login to DockerHub Registry
#         run: echo ${{ secrets.DOCKER_IMAGE_PASSWORD }} | docker login -u ${{ secrets.DOCKER_IMAGE_USERNAME }} --password-stdin

#       - name: Build and Push
#         run: |
#           docker-compose build
#           docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-admindashboard:1.0.0
#           docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-socialsphere:1.0.0
#           docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-Homepage:1.0.0



# name: Docker Image CI

# on:
#   push:
#     branches: [ "dev" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: "20.11.0"  

#       - name: Dependecies - Admin
#         run: |
#             npm install
#         env: 
#           CI: ""
#         working-directory: ./admindashboard

#       - name: Build - Admin
#         run: |
#             npm run build
#         working-directory: ./admindashboard

#       - name: Dependecies - SocialSphere
#         run: |
#             npm install
#         env:
#           CI: ""
#         working-directory: ./socialsphere

#       - name: Build - SocialSphere
#         run: |
#             npm run build
#         working-directory: ./socialsphere

#       - name: Dependecies - Homepage
#         run: |
#             npm install
#         env:
#           CI: ""
#         working-directory: ./Homepage

#       - name: Build - Homepage
#         run: |
#             npm run build
#         working-directory: ./Homepage
      
#       - name: Login to DockerHub Registry
#         run: echo ${{ secrets.DOCKER_IMAGE_PASSWORD }} | docker login -u ${{ secrets.DOCKER_IMAGE_USERNAME }} --password-stdin
        

#       - name: Build and Push
#         run: |
#             docker-compose build

#             docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-admindashboard:1.0.0
#             docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-socialsphere:1.0.0
#             docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-Homepage:1.0.0






name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"  

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Dependecies - Admin
        run: |
          npm install
        env: 
          CI: ""
        working-directory: ./admindashboard

      - name: Build - Admin
        run: |
          npm run build
        working-directory: ./admindashboard

      - name: Dependecies - SocialSphere
        run: |
          npm install
        env:
          CI: ""
        working-directory: ./socialsphere

      - name: Build - SocialSphere
        run: |
          npm run build
        working-directory: ./socialsphere

      - name: Dependecies - Homepage
        run: |
          npm install
        env:
          CI: ""
        working-directory: ./Homepage

      - name: Build - Homepage
        run: |
          npm run build
        working-directory: ./Homepage
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_IMAGE_PASSWORD }} | docker login -u ${{ secrets.DOCKER_IMAGE_USERNAME }} --password-stdin
        

      - name: Build and Push
        run: |
          docker-compose build

          docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-admindashboard:1.0.0
          docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-socialsphere:1.0.0
          docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/social-sphere-Homepage:1.0.0
